messes with partition tables

diff --git a/gentoo-base.d/gentoo-tools/edeclare b/gentoo-base.d/gentoo-tools/edeclare
--- a/gentoo-base.d/gentoo-tools/edeclare
+++ b/gentoo-base.d/gentoo-tools/edeclare
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 [[ $# -gt 1 ]] && echo "Usage: $(basename "$0") [--unsupervised]" && exit 1
-[[ ! -f /etc/portage/package.declare ]] && echo 'Aborting... missing configuration file: /etc/portage/package.declare!' && exit 1
+[[ ! -d /etc/portage/package.declare ]] && echo 'Aborting... missing configuration file: /etc/portage/package.declare!' && exit 1
 [[ ! -f /var/lib/portage/world ]] && echo 'Aborting... missing configuration file: /var/lib/portage/world!' && exit 1
 if [[ ${EUID} -ne 0 ]]; then
   doas "$0" "$@"
@@ -9,7 +9,7 @@ if [[ ${EUID} -ne 0 ]]; then
 fi
 
 INSTALLED_DEPENDENCIES=$(cat /var/lib/portage/world)
-DECLARED_DEPENDENCIES=$(sed --regexp-extended '/^[[:blank:]]*(#|$)/d; s/#.*//; s/[[:space:]]*$//' </etc/portage/package.declare)
+DECLARED_DEPENDENCIES=$(cat /etc/portage/package.declare/* | sed --regexp-extended '/^[[:blank:]]*(#|$)/d; s/#.*//; s/[[:space:]]*$//')
 ALL_DEPENDENCIES=$(echo "${INSTALLED_DEPENDENCIES} ${DECLARED_DEPENDENCIES}" | tr ' ' '\n' | sort | uniq)
 
 function is_declared { grep --quiet "^$1$" <<<"${DECLARED_DEPENDENCIES}"; }
