improves layering logic

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -61,13 +61,13 @@ function _main() {
     ! is_root && echo '[E] dots#install : missing required permissions' && return 1
     # sources target system configuration
     echo "[I] sourcing '$_HOST' configuration..."
-    _SCRIPT_TO_LOAD="hosts.d/$_HOST.d/configuration.conf"
-    source_file "$_SCRIPT_TO_LOAD" ||
+    _FILE_TO_LOAD="hosts.d/$_HOST.d/configuration.conf"
+    source_file "$_FILE_TO_LOAD" ||
       (echo "[E] dots#install : failed to source '$_HOST' configuration" && return 1)
     # installs gento to target system
     echo "[I] installing gentoo to '$_HOST'..."
-    _SCRIPT_TO_LOAD='dots-gentoo-installer'
-    source_file "$_SCRIPT_TO_LOAD" ||
+    _FILE_TO_LOAD='dots-gentoo-installer'
+    source_file "$_FILE_TO_LOAD" ||
       (echo "[E] dots#install : failed to install gentoo to '$_HOST'" && return 1)
     return 0
     ;;
@@ -76,7 +76,7 @@ function _main() {
   update) # resets dotfiles git repository and updates its head
     # checks required parameter
     _HOME="$(get_home "$@")" && _USER="$(get_user "$@")" ||
-      (echo "[E] dots#bootstrap : missing required parameter '--user'" && return 1)
+      (echo "[E] dots#update : missing required parameter '--user'" && return 1)
     # updates and resets local dotfiles git repository
     _main bootstrap && (
       echo '[I] updating dotfiles...'
@@ -89,23 +89,53 @@ function _main() {
     ;;
     # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
 
-  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
-  # clears deprecated directories and links after resetting them
-  sync)
+  sync) # merges dotfiles settings into the system
+    # checks required parameter
     _HOME="$(get_home "$@")" && _USER="$(get_user "$@")" ||
-      (echo '[E] missing required argument: --user' && return 1)
+      (echo "[E] dots#sync : missing required parameter '--user'" && return 1)
     _HOST="$(get_host "$@")" ||
-      (echo '[E] missing required argument: --host' && return 1)
-    export _HOME _HOST _USER
-
-    echo '[I] syncing dotfiles...' && run_script "hosts.d/$_HOST" "$@" ||
-      (echo "[E] failed to sync to ($_HOST)" && return 1)
+      (echo "[E] dots#sync : missing required parameter '--host'" && return 1)
+    # sources target system configuration
+    echo "[I] sourcing '$_HOST' configuration..."
+    _LAYERS=() && _FILE_TO_LOAD="hosts.d/$_HOST.d/configuration.conf"
+    source_file "$_FILE_TO_LOAD" ||
+      (echo "[E] dots#sync : failed to source '$_HOST' configuration" && return 1)
+    # synchronizes layer
+    echo "[I] syncing layers on '$_HOST'..."
+    for _LAYER in "${_LAYERS[@]}"; do
+      _FILE_TO_LOAD="$_LAYER/sync.sh"
+      [ ! -f "$_FILE_TO_LOAD" ] && continue
+      echo "[I] syncing layer '$_FILE_TO_LOAD'..."
+      source_file "$_FILE_TO_LOAD" ||
+        (echo "[E] dots#sync : failed to source '$_FILE_TO_LOAD'" && return 1)
+    done
+    # clears empty directories and stale links
+    ! get_option '--skip-cleaning' "$@" && (
+      ! is_root && (
+        echo "[I] cleaning empty directories and stale links from '$_HOME'..."
+        run_as_user "$_USER" clean_directories_and_links "$_HOME" ||
+          (echo "[E] dots#sync : failed to clean directories and links from '$_HOME'" && return 1)
+      )
+      is_root && (
+        echo "[I] cleaning empty directories and stale links from '/'..."
+        run_as_root clean_directories_and_links '/' ||
+          (echo "[E] dots#sync : failed to clean directories and links from '/'" && return 1)
+      )
+    )
+    # installs layer
+    echo "[I] installing layers on '$_HOST'..."
+    for _LAYER in "${_LAYERS[@]}"; do
+      _FILE_TO_LOAD="$_LAYER/install.sh"
+      [ ! -f "$_FILE_TO_LOAD" ] && continue
+      echo "[I] installing layer '$_FILE_TO_LOAD'..."
+      source_file "$_FILE_TO_LOAD" ||
+        (echo "[E] dots#sync : failed to source '$_FILE_TO_LOAD'" && return 1)
+    done
     return 0
     ;;
+    # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
 
-  # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
-  # handles unknown commands
-  *) usage && return 1 ;;
+  *) usage && return 1 ;; # handles unknown commands
   esac
 }
 _main "$@"
