adds tweaks to dots and scripts execution

diff --git a/dots-gentoo-installer b/dots-gentoo-installer
--- a/dots-gentoo-installer
+++ b/dots-gentoo-installer
@@ -1,26 +1,81 @@
 #!/bin/bash
+# shellcheck disable=SC2015 disable=SC2088 source=/dev/null
 set -eou pipefail
 
-# checks required variables
-[[ -z "$_DOTS_RAW_URL" ]] && echo "[E] missing required variable: \$_DOTS_RAW_URL" && exit 1
-[[ -z "$_GENTOO_RAW_URL" ]] && echo "[E] missing required variable: \$_GENTOO_RAW_URL" && exit 1
+# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
+# sources auxiliary functions
+_IS_DOTS_UTILS_LOADED=""
+source "$(dirname "$(readlink -f "$0")")/dots-utils" >/dev/null 2>&1 ||
+  source /dev/stdin <<<"$(curl -Lfs "$_DOTS_RAW_URL/dots-utils")"
+[ -z "$_IS_DOTS_UTILS_LOADED" ] && echo '[E] failed to source dots-utils' && exit 1
 
-[[ -z "$_DEV" ]] && echo "[E] missing required variable: \$_DEV" && exit 1
-[[ -z "$_BOOT" ]] && echo "[E] missing required variable: \$_BOOT" && exit 1
-[[ -z "$_ROOT" ]] && echo "[E] missing required variable: \$_ROOT" && exit 1
-[[ -z "$_HOST" ]] && echo "[E] missing required variable: \$_HOST" && exit 1
-[[ -z "$_USER" ]] && echo "[E] missing required variable: \$_USER" && exit 1
+function is_gpt() { get_option "--gpt" "$@"; }
+function is_mbr() { get_option "--mbr" "$@"; }
+
+# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
+# checks required variables
+[ -z "$_DOTS_RAW_URL" ] && echo "[E] missing required variable: \$_DOTS_RAW_URL" && exit 1
+[ -z "$_GENTOO_RAW_URL" ] && echo "[E] missing required variable: \$_GENTOO_RAW_URL" && exit 1
+
+[ -z "$_BOOT" ] && echo "[E] missing required variable: \$_BOOT" && exit 1
+[ -z "$_BOOT_SIZE" ] && echo "[E] missing required variable: \$_BOOT_SIZE" && exit 1
+[ -z "$_DEV" ] && echo "[E] missing required variable: \$_DEV" && exit 1
+[ -z "$_HOST" ] && echo "[E] missing required variable: \$_HOST" && exit 1
+[ -z "$_ROOT" ] && echo "[E] missing required variable: \$_ROOT" && exit 1
+[ -z "$_ROOT_SIZE" ] && echo "[E] missing required variable: \$_ROOT_SIZE" && exit 1
+[ -z "$_USER" ] && echo "[E] missing required variable: \$_USER" && exit 1
+
+! is_gpt "$@" && ! is_mbr "$@" && echo '[E] missing required argument: --gpt or --mbr' && exit 1
 
 # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
 # gathers required inputs for installation
-if [[ -z $_PASSWORD ]]; then
-  echo -e "\nGathering installation setup..."
-  while true; do
-    read -r -s -p ' - System password: ' _PASSWORD && echo
-    [[ -z $_PASSWORD ]] && continue
-    read -r -s -p ' - Confirm system password: ' _PASSWORD_CONFIRMATION && echo
-    [[ "$_PASSWORD" == "$_PASSWORD_CONFIRMATION" ]] && break
-  done
+echo -e "\nGathering installation setup..."
+while true; do
+  read -r -s -p ' - System password: ' _PASSWORD && echo
+  [[ -z $_PASSWORD ]] && continue
+  read -r -s -p ' - Confirm system password: ' _PASSWORD_CONFIRMATION && echo
+  [[ "$_PASSWORD" == "$_PASSWORD_CONFIRMATION" ]] && break
+done
+
+# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
+# deletes all partitions in the system device and creates defined layout
+wipefs -a "$_DEV"
+if is_gpt; then
+  sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' <<EOF | fdisk "$_DEV"
+    g  # create empty gpt partition table
+    n  # create boot partition
+       # choose default partition number
+       # choose default sector
+    $_BOOT_SIZE
+    t  # choose partition type
+    1  # choose efi system
+    n  # create root partition
+       # choose default partition number
+       # choose default sector
+    $_ROOT_SIZE
+    t  # choose partition type
+       # choose default partition number
+    23 # choose linux root
+    p  # print partition table
+    w  # write changes to disk
+EOF
+elif is_mbr; then
+  sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' <<EOF | fdisk "$_DEV"
+    o  # create empty mbr partition table
+    n  # create boot partition
+       # choose default partition type
+       # choose default partition number
+       # choose default sector number
+    $_BOOT_SIZE
+    a  # mark partition as bootable
+    n  # create root partition
+       # choose default partition type
+       # choose default partition number
+       # choose default sector number
+    $_ROOT_SIZE
+    p  # print partition table
+    w  # write changes to disk
+EOF
 fi
 
 # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
diff --git a/dots-utils b/dots-utils
--- a/dots-utils
+++ b/dots-utils
@@ -53,8 +53,11 @@ function get_option() {
 #   0 (success) if user is found
 #   1 (failure) if user is not found
 function get_user() {
-  _USER="$( (is_root && get_first_wheel_user) || (! is_root && whoami) || get_option "--username" "$@")"
-  [[ -n "$_USER" ]] && echo "$_USER" || return 1
+  _USER="$(get_option "--user" "$@")" || true
+  [[ -n "$_USER" ]] && echo "$_USER" && return 0
+  is_root && get_first_wheel_user && return 0 || true
+  ! is_root && whoami && return 0 || true
+  return 1
 }
 
 # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
@@ -67,22 +70,24 @@ function get_user() {
 #   1 (failure) if path is not found
 function get_home() {
   _USER="$(get_user "$@")" || return 1
-  test "$(uname)" == 'Darwin' && _HOME="/Users/$_USER"
-  test "$(uname)" == 'Linux' && _HOME="/home/$_USER"
-  [[ -n "$_HOME" ]] && echo "$_HOME" || return 1
+  [ "$(uname)" == 'Darwin' ] && echo "/Users/$_USER" && return 0 || true
+  [ "$(uname)" == 'Linux' ] && echo "/home/$_USER" && return 0 || true
+  return 1
 }
 
 # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
-# gets the hostname of the system executing the script
+# gets the host of the system executing the script
 # arguments:
-#   none
+#   $@ - the parent script arguments
 # returns:
-#   the hostname, printed to standard output
-#   0 (success) if hostname is found
-#   1 (failure) if hostname is not found
-function get_hostname() {
-  test "$(uname)" == 'Darwin' && hostname && return 0
-  test "$(uname)" == 'Linux' && cat /etc/hostname 2>/dev/null && return 0
+#   the host, printed to standard output
+#   0 (success) if host is found
+#   1 (failure) if host is not found
+function get_host() {
+  _HOST="$(get_option "--host" "$@")" || true
+  [[ -n "$_HOST" ]] && echo "$_HOST" && return 0
+  [ "$(uname)" == 'Darwin' ] && hostname && return 0 || true
+  [ "$(uname)" == 'Linux' ] && cat /etc/hostname 2>/dev/null && return 0 || true
   return 1
 }
 
@@ -103,18 +108,15 @@ function is_root() { test $EUID -eq 0; }
 # returns:
 #   the exit status of the executed command
 function run_as_root() {
-  is_root && {
+  if is_root; then
     "$@"
-    return
-  }
-  check_command doas && {
+  elif check_command doas; then
     doas "$@"
-    return
-  }
-  check_command sudo && {
+  elif check_command sudo; then
     sudo "$@"
-    return
-  }
+  else
+    return 1
+  fi
 }
 
 # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
@@ -126,3 +128,25 @@ function run_as_root() {
 # returns:
 #   the exit status of the executed command
 function run_as_user() { if is_root; then su "$1" -c "${*:2}"; else "${@:2}"; fi; }
+
+# ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
+# runs a script from the local filesystem or directly from github
+# arguments:
+#   $1 - the relative path to the script to execute from the base dotfiles directory
+#   $@ - all subsequent arguments, which form the command and its arguments
+#        to be executed (e.g., 'install', 'sync')
+# returns:
+#   the exit status of the executed command
+#   1 (failure) if any failure occurs
+function run_script() {
+  _HOME="$(get_home "$@")" || return 1
+  _LOCAL_SCRIPT="$_HOME/$_DOTS_DIR/$1"
+  _REMOTE_SCRIPT="$_DOTS_RAW_URL/$1"
+  if [ -f "$_LOCAL_SCRIPT" ]; then
+    bash "$_LOCAL_SCRIPT" "${*:2}"
+  elif curl -ILs "$_REMOTE_SCRIPT" >/dev/null; then
+    curl -Lfs "$_REMOTE_SCRIPT" | bash -s -- "${*:2}"
+  else
+    return 1
+  fi
+}
