adds new maintenance scripts

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -2,7 +2,6 @@
 # shellcheck disable=SC2015 disable=SC2088 source=/dev/null
 set -eou pipefail
 
-# constants
 export _DOTS_DIR='workspace/personal/dotfiles'
 export _DOTS_RAW_URL='https://raw.githubusercontent.com/pedro-pereira-dev/dotfiles/refs/heads/main'
 export _DOTS_URL='https://github.com/pedro-pereira-dev/dotfiles.git'
@@ -17,10 +16,11 @@ source "$(dirname "$(readlink -f "$0")")/dots-utils" >/dev/null 2>&1 ||
 [ -z "$_IS_DOTS_UTILS_LOADED" ] && echo '[E] failed to source dots-utils' && exit 1
 
 function _main() {
-  case $1 in
+  _CMD='' && [ "$#" -ge 1 ] && _CMD="$1"
+  case $_CMD in
 
   # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
-  # installs required software and clones dotfiles
+  # installs required software and clones dotfiles git repository
   bootstrap)
     _HOME="$(get_home "$@")" && _USER="$(get_user "$@")" ||
       (echo '[E] missing required argument: --user' && return 1)
@@ -41,19 +41,20 @@ function _main() {
     ;;
 
   # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
-  # sets up live iso system and runs custom gentoo installation script
+  # prepares live iso system and installs gentoo using custom script
   install)
     _HOME="$(get_home "$@")" ||
       (echo '[E] missing required argument: --user' && return 1)
     _HOST="$(get_host "$@")" ||
       (echo '[E] missing required argument: --host' && return 1)
+    ! is_root && echo '[E] missing required permissions' && return 1
     run_script "hosts/$_HOST" "$@" ||
       (echo "[E] failed to install gentoo to ($_HOST)" && return 1)
     return 0
     ;;
 
   # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
-  # clears deprecated files and directories, and updates the dotfiles repository
+  # resets dotfiles git repository and updates its head
   update)
     _HOME="$(get_home "$@")" && _USER="$(get_user "$@")" ||
       (echo '[E] missing required argument: --user' && return 1)
@@ -66,9 +67,9 @@ function _main() {
     ;;
 
   # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
-  # clears setup and applies dotfiles to system
+  # clears deprecated directories and links after resetting them
   sync)
-    _HOME="$(get_home "$@")" ||
+    _HOME="$(get_home "$@")" && _USER="$(get_user "$@")" ||
       (echo '[E] missing required argument: --user' && return 1)
     _HOST="$(get_host "$@")" ||
       (echo '[E] missing required argument: --host' && return 1)
@@ -79,19 +80,7 @@ function _main() {
 
   # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
   # handles unknown commands
-  *)
-    [[ -n "$1" ]] && echo "[E] unknown command ($1)"
-    [[ -z "$1" ]] && echo -e "\
-dots: command-line interface for managing dotfiles and gentoo systems installations
-Usage:
-  dots bootstrap  [ --user <user> ]                   >> installs git and clones dotfiles repository
-  dots install      --host <host>                     >> installs gentoo on the target system 'host'
-  dots update     [ --user <user> ]                   >> clears and updates the dotfiles directory
-  dots sync       [ --host <host> ] [ --user <user> ] >> clears setup and applies dotfiles to system
-"
-    return 1
-    ;;
-
+  *) usage && return 1 ;;
   esac
 }
 _main "$@"
diff --git a/hosts/bra-m0064 b/hosts/bra-m0064
--- a/hosts/bra-m0064
+++ b/hosts/bra-m0064
@@ -2,6 +2,16 @@
 # shellcheck disable=SC2015 disable=SC2088 source=/dev/null
 set -eou pipefail
 
+export _DEV='/dev/sda'
+export _BOOT='/dev/sda1'
+export _ROOT='/dev/sda2'
+export _HOST='gentoo-server-hetzner-proxy'
+export _USER='chuck'
+
+export _BOOT_SIZE='+512M'
+export _ROOT_SIZE=' '
+export _TABLE_TYPE='--mbr'
+
 # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
 # sources auxiliary functions
 _IS_DOTS_UTILS_LOADED=""
@@ -10,25 +20,26 @@ source "$(dirname "$(readlink -f "$0")")/../dots-utils" >/dev/null 2>&1 ||
 [ -z "$_IS_DOTS_UTILS_LOADED" ] && echo '[E] failed to source dots-utils' && exit 1
 
 function _main() {
-  case $1 in
+  _CMD='' && [ "$#" -ge 1 ] && _CMD="$1"
+  case $_CMD in
 
   # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
-  # clears setup and applies dotfiles to system
+  # clears deprecated directories and links after resetting them
   sync)
-    _HOME="$(get_home "$@")" && _HOST="$(get_host "$@")"
-    is_root && echo '[E] failed because it should not run as root' && return 1
+    _HOME="$(get_home "$@")" && _HOST="$(get_host "$@")" && _USER="$(get_user "$@")"
+    is_root && echo '[E] failed cannot run as root' && return 1
     stow_directory 'default' ||
       (echo "[E] failed to symlink files for (default)" && return 1)
     stow_directory "$_HOST" ||
       (echo "[E] failed to symlink files for ($_HOST)" && return 1)
-    clean_directories_and_links "$_HOME" ||
+    run_as_user "$_USER" clean_directories_and_links "$_HOME" ||
       (echo '[E] failed to clean directories and links' && return 1)
     return 0
     ;;
 
   # ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- ----- -----
   # handles unknown commands
-  *) echo "[E] unknown command ($1)" && return 1 ;;
+  *) usage && return 1 ;;
   esac
 }
 _main "$@"
