chore: adds refactors

diff --git a/shared/gentoo/esuite/edeclare b/shared/gentoo/esuite/edeclare
--- a/shared/gentoo/esuite/edeclare
+++ b/shared/gentoo/esuite/edeclare
@@ -2,24 +2,25 @@
 set -eo pipefail
 
 [[ $# -gt 1 ]] && echo "Usage: $(basename "$0") [--unsupervised]" && exit 1
-[[ ! -f /etc/portage/package.declare ]] && echo 'Missing configuration: /etc/portage/package.declare' && exit 1
+[[ ! -f /etc/portage/package.declare ]] && echo 'Aborting... missing configuration file: /etc/portage/package.declare!' && exit 1
+[[ ! -f /var/lib/portage/world ]] && echo 'Aborting... missing configuration file: /var/lib/portage/world!' && exit 1
 [[ ${EUID} -ne 0 ]] && su root -c "$0" "$@" && exit $?
-
-function is_declared { grep --quiet "^$1$" <<<"${DECLARED_DEPENDENCIES}"; }
-function is_installed { grep --quiet "^$1$" <<<"${INSTALLED_DEPENDENCIES}"; }
 
 INSTALLED_DEPENDENCIES=$(cat /var/lib/portage/world)
 DECLARED_DEPENDENCIES=$(sed --regexp-extended '/^[[:blank:]]*(#|$)/d; s/#.*//; s/[[:space:]]*$//' </etc/portage/package.declare)
 ALL_DEPENDENCIES=$(echo "${INSTALLED_DEPENDENCIES} ${DECLARED_DEPENDENCIES}" | tr ' ' '\n' | sort | uniq)
 
+function is_declared { grep --quiet "^$1$" <<<"${DECLARED_DEPENDENCIES}"; }
+function is_installed { grep --quiet "^$1$" <<<"${INSTALLED_DEPENDENCIES}"; }
+
 declare -a INSTALL=()
 declare -a REMOVE=()
 
-for DEPENDENCIES in ${ALL_DEPENDENCIES}; do
-  if ! is_installed "${DEPENDENCIES}" && is_declared "${DEPENDENCIES}"; then
-    INSTALL+=("${DEPENDENCIES}")
-  elif is_installed "${DEPENDENCIES}" && ! is_declared "${DEPENDENCIES}"; then
-    REMOVE+=("${DEPENDENCIES}")
+for DEPENDENCY in ${ALL_DEPENDENCIES}; do
+  if ! is_installed "${DEPENDENCY}" && is_declared "${DEPENDENCY}"; then
+    INSTALL+=("${DEPENDENCY}")
+  elif is_installed "${DEPENDENCY}" && ! is_declared "${DEPENDENCY}"; then
+    REMOVE+=("${DEPENDENCY}")
   fi
 done
 
diff --git a/shared/scripts/secrets/secrets-set b/shared/scripts/secrets/secrets-set
--- a/shared/scripts/secrets/secrets-set
+++ b/shared/scripts/secrets/secrets-set
@@ -3,22 +3,18 @@ set -eo pipefail
 
 [[ ${EUID} -eq 0 ]] && echo 'Aborting... cannot run as root!' && exit 1
 [[ $# -ne 1 ]] && echo "Usage: $(basename "$0") <secret-name>" && exit 1
+[[ ! -d /home/$(whoami)/workspace/personal/dotfiles-secrets ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1
+[[ -d /home/$(whoami)/.ssh/secrets/$1 ]] && echo "Aborting... /home/$(whoami)/.ssh/secrets/$1 already exists!" && exit 0
+[[ ! -f /home/$(whoami)/workspace/personal/dotfiles-secrets/$1.tar.enc ]] &&
+  echo "Aborting... /home/$(whoami)/workspace/personal/dotfiles-secrets/$1.tar.enc does not exist!" && exit 1
 
-SYSTEM_USER=$(whoami)
-
-DOTFILES_SECRETS_DIR="/home/${SYSTEM_USER}/workspace/personal/dotfiles-secrets"
-SECRETS_DIR="/home/${SYSTEM_USER}/.ssh/secrets"
 SECRET_TAR=$(mktemp)
 
-[[ ! -d ${DOTFILES_SECRETS_DIR} ]] && echo 'Aborting... dotfiles-secrets was not cloned!' && exit 1
-[[ -d ${SECRETS_DIR}/$1 ]] && echo "Aborting... ${SECRETS_DIR}/$1 already exists!" && exit 0
-[[ ! -f ${DOTFILES_SECRETS_DIR}/$1.tar.enc ]] && echo "Aborting... ${DOTFILES_SECRETS_DIR}/$1.tar.enc does not exist!" && exit 1
-
-mkdir --parents "${SECRETS_DIR}"
+mkdir --parents "/home/$(whoami)/.ssh/secrets"
 while true; do
-  echo "Setting up ${DOTFILES_SECRETS_DIR}/$1.tar.enc: "
-  gpg --pinentry-mode loopback --quiet --decrypt "${DOTFILES_SECRETS_DIR}/$1.tar.enc" >"${SECRET_TAR}" && break
+  echo "Setting up /home/$(whoami)/workspace/personal/dotfiles-secrets/$1.tar.enc: "
+  gpg --pinentry-mode loopback --quiet --decrypt "/home/$(whoami)/workspace/personal/dotfiles-secrets/$1.tar.enc" >"${SECRET_TAR}" && break
   echo -e '\nPassword is not correct!'
 done
-tar --directory "${SECRETS_DIR}" --extract --file "${SECRET_TAR}"
+tar --directory "/home/$(whoami)/.ssh/secrets" --extract --file "${SECRET_TAR}"
 rm --force "${SECRET_TAR}"
